# version: "3.9"
services:
  mysql-lti:
    image: mysql:9
    # command: --default-authentication-plugin=mysql_native_password
    # restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      # MYSQL_DATABASE: "lti"
      # MYSQL_USER: "lti_local"
      # MYSQL_PASSWORD: "Lti@123"
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - "lti_nuxt_mysql_data:/var/lib/mysql"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

volumes:
  lti_nuxt_mysql_data:
    driver: local
